#!/bin/bash

echo -e "KKKKKKKKK    KKKKKKK               CCCCCCCCCCCCC         DDDDDDDDDDDDD"        
echo -e "K:::::::K    K:::::K            CCC::::::::::::C         D::::::::::::DDD"     
echo -e "K:::::::K    K:::::K          CC:::::::::::::::C         D:::::::::::::::DD"   
echo -e "K:::::::K   K::::::K         C:::::CCCCCCCC::::C         DDD:::::DDDDD:::::D"  
echo -e "KK::::::K  K:::::KKK        C:::::C       CCCCCC           D:::::D    D:::::D" 
echo -e "  K:::::K K:::::K          C:::::C                         D:::::D     D:::::D"
echo -e "  K::::::K:::::K           C:::::C                         D:::::D     D:::::D"
echo -e "  K:::::::::::K            C:::::C                         D:::::D     D:::::D"
echo -e "  K:::::::::::K            C:::::C                         D:::::D     D:::::D"
echo -e "  K::::::K:::::K           C:::::C                         D:::::D     D:::::D"
echo -e "  K:::::K K:::::K          C:::::C                         D:::::D     D:::::D"
echo -e "KK::::::K  K:::::KKK        C:::::C       CCCCCC           D:::::D    D:::::D" 
echo -e "K:::::::K   K::::::K         C:::::CCCCCCCC::::C         DDD:::::DDDDD:::::D"  
echo -e "K:::::::K    K:::::K          CC:::::::::::::::C         D:::::::::::::::DD"   
echo -e "K:::::::K    K:::::K            CCC::::::::::::C         D::::::::::::DDD"     
echo -e "KKKKKKKKK    KKKKKKK               CCCCCCCCCCCCC         DDDDDDDDDDDDD" 
